### ISSUE TITLE
How to set dt.entity.host

### ISSUE THREAD

**Issue by dieselsteve** [dynatrace-oss/logstash-output-dynatrace#12]
Hi all, 

I need to set the dt.entity.host when configuring the output in the logstash config so I can find the logs later on in the Dynatrace log explorer...

Any Ideas?

rgds Steve

**Comment by arminru** [comment]
Hi @dieselsteve!
You can use the feature described here which will work for logs as well: https://www.dynatrace.com/support/help/how-to-use-dynatrace/metrics/metric-ingestion/ingestion-methods/enrich-metrics/
This will allow you get the entity metadata from the OneAgent which you can then add as attributes to your log messages.

**Comment by dieselsteve** [comment]
Hi arminru,

thanks for the answer but unfortunately it doesn't help me as I don't have a oneagent in the game. I want to collect okta system log entries as described in https://github.com/SecurityRiskAdvisors/logstash-input-okta_system_log/blob/master/docs/index.asciidoc and then send them to Dynatrace and stich them to a specific custom Device which already exists so I can separate them from all other logfiles. Do you have any idea how to achieve that?

rgds Steve

**Comment by arminru** [comment]
If you already have the value for `dt.entity.host` (i.e., the respective ID starting with `HOST-`) ready, then you can use the `mutate` filter plugin with the `add_field` option and add it to your Logstash pipeline:
https://www.elastic.co/guide/en/logstash/current/plugins-filters-mutate.html#plugins-filters-mutate-add_field
The full list of well-known attributes/fields picked up by the Dynatrace Log Ingest API can be found here and there is a dedicated one for custom devices as well:
https://www.dynatrace.com/support/help/dynatrace-api/environment-api/log-monitoring-v2/post-ingest-logs/#body-format

**Comment by dieselsteve** [comment]
Hey arminru,

many thanks that did the trick!!

rgds Steve

**Comment by arminru** [comment]
You're welcome! Glad I was able to help 🙂
