### ISSUE TITLE
Dynatrace gives a Bad Request

### ISSUE THREAD

**Issue by heydenb** [dynatrace-oss/logstash-output-dynatrace#19]
[2022-07-28T16:41:03,119][ERROR][logstash.outputs.dynatrace][main][dynatrace_nonprod] Dynatrace returned 400 Bad Request

Currently I have no idea why this is. There are probably limitations at API level, but I don't know now if the message is to long or someting else.

**Comment by dyladan** [comment]
This isn't really enough information to know exactly what happened. There are some API level limits but I can't really say which you are hitting if any. Does this happen on every log line, occasionally, rarely, or just once? If you can [enable debug logging](https://github.com/dynatrace-oss/logstash-output-dynatrace#enable-debug-logs) to gather more information as well then we may be able to pinpoint what is going on.

**Comment by heydenb** [comment]
Hey Daniel, this suggestion is not to solve this specific issue. Found it already. But the api returns a message when there is a Bad Request. A very useful message. If you could just print it out when it occurs, the troubleshooting is a lot easier.

**Comment by dyladan** [comment]
Client errors now log request bodies as of 0.3.0
